#!/usr/bin/env node
/*
 * print-extras.js — generate a printable, self-contained HTML sheet of the
 * art-only cards: the Bank Loan card and the Hot Tip ("Look at the top insider
 * tip card") starter card. Each is pure art with no overlay, so we just tile it.
 *
 * Each card is sized so its LONGEST edge prints at 3.5in (matching the rest of
 * the deck: goal cards are 3.5in wide, stock cards 3.5in tall). The art's own
 * aspect ratio sets the other edge — nothing is stretched.
 *
 * Images are embedded as base64 → the output HTML is one standalone file you can
 * open directly (file://) and print at true size.
 *
 * Usage:
 *   node cards/print-extras.js [--assets <dir>] [--out <file>]
 *     --assets  Folder with loan-card.png and hottip-card.png. Default: cards/assets
 *     --out     Output HTML path. Default: cards/print-extras.html
 */

const fs = require('fs');
const path = require('path');

const LONG_EDGE_IN = 3.5;

// Which art-only cards to print, and how many copies of each.
const SHEET = [
  { asset: 'loan-card',   label: 'Bank Loan', count: 6 },
  { asset: 'hottip-card', label: 'Hot Tip',   count: 6 },
];

// ---------------------------------------------------------------------------
// Args
// ---------------------------------------------------------------------------
function parseArgs(argv) {
  const args = { assets: null, out: null, help: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--assets') args.assets = argv[++i];
    else if (a === '--out') args.out = argv[++i];
    else if (a === '-h' || a === '--help') args.help = true;
    else throw new Error(`Unknown argument: ${a}`);
  }
  return args;
}

// ---------------------------------------------------------------------------
// Asset loading → base64 data URI + intrinsic pixel size (read from PNG header)
// ---------------------------------------------------------------------------
const MIME = { '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.webp': 'image/webp' };
const EXT_ORDER = ['.png', '.jpg', '.jpeg', '.webp'];

// PNG: IHDR width/height are big-endian uint32 at byte offsets 16 and 20.
function pngSize(buf) {
  return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
}

function loadAsset(assetsDir, base) {
  for (const ext of EXT_ORDER) {
    const file = path.join(assetsDir, base + ext);
    if (fs.existsSync(file)) {
      const buf = fs.readFileSync(file);
      const size = ext === '.png' ? pngSize(buf) : null; // only PNGs carry size here
      return { uri: `data:${MIME[ext]};base64,${buf.toString('base64')}`, size };
    }
  }
  return null;
}

// ---------------------------------------------------------------------------
// HTML
// ---------------------------------------------------------------------------
function escapeHtml(s) {
  if (s == null) return '';
  return String(s)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

// Card dimensions in inches with the long edge pinned to LONG_EDGE_IN.
function cardDims(size) {
  const { w, h } = size;
  if (w >= h) return { w: LONG_EDGE_IN, h: LONG_EDGE_IN * h / w };
  return { w: LONG_EDGE_IN * w / h, h: LONG_EDGE_IN };
}

// Embed each unique image once as a class (not inlined per card copy).
function imageCss(items) {
  return items
    .map(it => `  .e-${it.asset} { background: url("${it.uri}") center / 100% 100% no-repeat; }`)
    .join('\n') + '\n';
}

function cardDivs(items) {
  const cards = [];
  for (const it of items) {
    const d = cardDims(it.size);
    const style = `width:${d.w.toFixed(4)}in;height:${d.h.toFixed(4)}in`;
    for (let i = 0; i < it.count; i++) {
      cards.push(`    <div class="card" style="${style}"><div class="art e-${it.asset}"></div></div>`);
    }
  }
  return cards;
}

function renderHtml(items, total, meta) {
  const cards = cardDivs(items);
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Insider Trading — Printable Loan &amp; Hot Tip Cards</title>
<!-- Generated by cards/print-extras.js. Do not edit by hand; re-run the script.
     Assets: ${escapeHtml(meta.assetsDir)} · ${total} cards -->
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }

  body {
    font-family: Georgia, serif;
    background: #ffffff;
    color: #2c2c2c;
    padding: 24px;
  }

  .toolbar {
    max-width: 1100px; margin: 0 auto 20px;
    display: flex; align-items: baseline; gap: 16px; flex-wrap: wrap;
  }
  .toolbar h1 { font-size: 20px; font-weight: 700; }
  .toolbar .meta { font-size: 13px; opacity: 0.75; }

  .sheet {
    display: flex; flex-wrap: wrap; gap: 0.16in;
    justify-content: center; max-width: 1100px; margin: 0 auto;
  }

  .card {
    position: relative;
    line-height: 0;
    box-shadow: 0 4px 14px rgba(0,0,0,0.4);
  }
  .art { display: block; width: 100%; height: 100%; }
${imageCss(items)}
  @media print {
    @page { size: letter portrait; margin: 0.2in; }
    body { background: #fff; padding: 0; }
    .toolbar { display: none; }
    .sheet { gap: 0; max-width: none; justify-content: flex-start; }
    .card {
      box-shadow: none;
      page-break-inside: avoid; break-inside: avoid;
      -webkit-print-color-adjust: exact; print-color-adjust: exact;
    }
  }
</style>
</head>
<body>
  <div class="toolbar">
    <h1>Printable Loan &amp; Hot Tip Cards</h1>
    <span class="meta">${total} cards · true size (3.5in long edge) · Cmd/Ctrl-P to print</span>
  </div>
  <div class="sheet">
${cards.join('\n')}
  </div>
</body>
</html>
`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
function main() {
  let args;
  try {
    args = parseArgs(process.argv.slice(2));
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
  if (args.help) {
    console.log('Usage: node cards/print-extras.js [--assets <dir>] [--out <file>]');
    return;
  }

  const cardsDir = __dirname;
  const assetsDir = path.resolve(args.assets || path.join(cardsDir, 'assets'));
  const outPath = path.resolve(args.out || path.join(cardsDir, 'print-extras.html'));

  const items = [];
  for (const entry of SHEET) {
    const loaded = loadAsset(assetsDir, entry.asset);
    if (!loaded || !loaded.size) {
      console.error(`✗ Missing or non-PNG asset: ${entry.asset} in ${assetsDir}`);
      process.exit(1);
    }
    items.push({ ...entry, uri: loaded.uri, size: loaded.size });
  }

  const total = items.reduce((n, it) => n + it.count, 0);
  const html = renderHtml(items, total, { assetsDir });
  fs.writeFileSync(outPath, html);

  console.log(`✓ Wrote ${total} cards → ${path.relative(process.cwd(), outPath)}`);
  for (const it of items) {
    const d = cardDims(it.size);
    console.log(`  ${it.label}: ${it.count}× at ${d.w.toFixed(2)}in × ${d.h.toFixed(2)}in`);
  }
}

// ---------------------------------------------------------------------------
// Scoped fragment for the combined print-all sheet (namespaced .cat-extras).
// Cards carry inline width/height, so no extra CSS is needed beyond shared.
// ---------------------------------------------------------------------------
function buildFragment(assetsDir) {
  const items = SHEET.map(entry => {
    const loaded = loadAsset(assetsDir, entry.asset);
    if (!loaded || !loaded.size) throw new Error(`Missing extras asset: ${entry.asset}`);
    return { ...entry, uri: loaded.uri, size: loaded.size };
  });
  const cards = cardDivs(items);
  return {
    css: imageCss(items),
    body: `  <section class="cat cat-extras">\n    <h2>Loan & Hot Tip Cards (${cards.length})</h2>\n    <div class="sheet">\n${cards.join('\n')}\n    </div>\n  </section>`,
    script: '',
  };
}

module.exports = { buildFragment };

if (require.main === module) main();
