#!/usr/bin/env node
/*
 * print-all.js — generate ONE printable, self-contained HTML sheet containing
 * every non-stock card type: goal, action, insider tip, and loan + hot tip.
 * (Stock cards are printed separately via print-cards.js.)
 *
 * It pulls a scoped fragment ({ css, body, script }) from each per-type
 * generator and stitches them into a single document. Each fragment's CSS is
 * namespaced under a .cat-<type> class so the layouts don't collide, and the
 * card art/fonts are embedded as base64 → the output is one standalone file.
 *
 * Usage:
 *   node cards/print-all.js [--assets <dir>] [--out <file>]
 *     --assets  Asset folder. Default: cards/assets
 *     --out     Output HTML path. Default: cards/print-all.html
 */

const fs = require('fs');
const path = require('path');

const goals = require('./print-goals.js');
const actions = require('./print-actions.js');
const tips = require('./print-tips.js');
const extras = require('./print-extras.js');

// Order on the sheet (grouped by orientation: landscape goals, portrait rest).
const SECTIONS = [goals, actions, tips, extras];

function parseArgs(argv) {
  const args = { assets: null, out: null, help: false };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--assets') args.assets = argv[++i];
    else if (a === '--out') args.out = argv[++i];
    else if (a === '-h' || a === '--help') args.help = true;
    else throw new Error(`Unknown argument: ${a}`);
  }
  return args;
}

function loadFontFace(assetsDir) {
  const file = path.join(assetsDir, 'fonts', 'source-serif-pro-400.woff2');
  if (fs.existsSync(file)) {
    const b64 = fs.readFileSync(file).toString('base64');
    return `@font-face {
      font-family: 'Source Serif Pro';
      font-style: normal; font-weight: 400; font-display: swap;
      src: url(data:font/woff2;base64,${b64}) format('woff2');
    }`;
  }
  return `@import url('https://fonts.googleapis.com/css2?family=Source+Serif+Pro:wght@400&display=swap');`;
}

function renderHtml(fragments, fontFace) {
  const css = fragments.map(f => f.css).filter(Boolean).join('\n');
  const body = fragments.map(f => f.body).join('\n');
  const scripts = fragments.map(f => f.script).filter(Boolean).join('\n');
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Insider Trading — Printable Cards (All Except Stock)</title>
<!-- Generated by cards/print-all.js. Do not edit by hand; re-run the script. -->
<style>
  @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@600;700&family=Playfair+Display:wght@800;900&display=swap');
  ${fontFace}

  * { margin: 0; padding: 0; box-sizing: border-box; }

  body {
    font-family: 'Source Serif Pro', Georgia, serif;
    background: #ffffff;
    color: #2c2c2c;
    padding: 24px;
  }

  .cat { max-width: 1100px; margin: 0 auto 28px; }
  .cat h2 { font: 700 16px Georgia, serif; color: #555; margin: 0 0 10px; }

  .sheet {
    display: flex; flex-wrap: wrap; gap: 0.16in;
    justify-content: center;
  }

  .card {
    position: relative;
    line-height: 0;
    box-shadow: 0 4px 14px rgba(0,0,0,0.4);
  }
  .art { display: block; width: 100%; height: 100%; }

  /* Per-type scoped layout. */
${css}

  @media print {
    @page { size: letter portrait; margin: 0.2in; }
    body { background: #fff; padding: 0; }
    .cat { max-width: none; margin: 0; }
    .cat h2 { display: none; }
    .sheet { gap: 0; justify-content: flex-start; }
    .card {
      box-shadow: none;
      page-break-inside: avoid; break-inside: avoid;
      -webkit-print-color-adjust: exact; print-color-adjust: exact;
    }
  }
</style>
</head>
<body>
${body}
  <script>
${scripts}
  </script>
</body>
</html>
`;
}

function main() {
  let args;
  try {
    args = parseArgs(process.argv.slice(2));
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
  if (args.help) {
    console.log('Usage: node cards/print-all.js [--assets <dir>] [--out <file>]');
    return;
  }

  const cardsDir = __dirname;
  const assetsDir = path.resolve(args.assets || path.join(cardsDir, 'assets'));
  const outPath = path.resolve(args.out || path.join(cardsDir, 'print-all.html'));

  let fragments;
  try {
    fragments = SECTIONS.map(m => m.buildFragment(assetsDir));
  } catch (e) {
    console.error(`✗ ${e.message}`);
    process.exit(1);
  }

  const html = renderHtml(fragments, loadFontFace(assetsDir));
  fs.writeFileSync(outPath, html);

  console.log(`✓ Wrote combined sheet → ${path.relative(process.cwd(), outPath)}`);
}

main();
