/**
 * Goal Card - represents a goal card with stock change, goal, and reward
 *
 * Uses pre-parsed data from goal_cards.json (generated by generate_goal_cards.py)
 * No runtime parsing needed - all parsing done at generation time for efficiency
 */
import { Card } from './Card.js';
import { CARD_TYPES } from '../utils/Constants.js';

export class GoalCard extends Card {
  constructor(data) {
    super(CARD_TYPES.GOAL, data);

    // Store human-readable text for UI display
    this.stockChange = data.stockChange?.text || data.stockChange;
    this.goal = data.goal?.text || data.goal;
    this.reward = data.reward?.text || data.reward;

    // Store metadata with pre-parsed data
    this.metadata = {
      ...(data.metadata || {}),
      // Pre-parsed data from JSON (generated by Python)
      stockChangeParsed: data.stockChange?.parsed,
      stockChangeType: data.stockChange?.type,
      goalParsed: data.goal?.parsed,
      rewardParsed: data.reward?.parsed
    };

    this.revealed = data.revealed !== undefined ? data.revealed : false;
  }

  /**
   * Mark the goal as revealed
   */
  reveal() {
    this.revealed = true;
  }

  /**
   * Get a plain object representation of the card
   * @returns {Object}
   */
  toJSON() {
    return {
      ...super.toJSON(),
      stockChange: this.stockChange,
      goal: this.goal,
      reward: this.reward,
      metadata: this.metadata,
      revealed: this.revealed
    };
  }

  /**
   * Create a goal card from a plain object
   * @param {Object} data - Goal card data
   * @returns {GoalCard}
   */
  static fromJSON(data) {
    return new GoalCard(data);
  }
}
